[google]
client_id = "859044972753-r2h35gl7gmpp088b1q5osjd55964vss9.apps.googleusercontent.com"
client_secret = "YOUR_GOOGLE_CLIENT_SECRET"
redirect_uri = "http://localhost:8501"

[general]
allowed_emails = ["your_email@gmail.com", "friend@gmail.com"]
