[google]
client_id = "859044972753-r2h35gl7gmpp088b1q5osjd55964vss9.apps.googleusercontent.com"
client_secret = "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"
redirect_uri = "https://ffinfotrack.streamlit.app"

[general]
allowed_emails = ["nazmusshakibshihan01@gmail.com", "..."]
