[google]
client_id = "859044972753-r2h35gl7gmpp088b1q5osjd55964vss9.apps.googleusercontent.com"
client_secret = "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"
redirect_uri = "http://localhost:8501"

[general]
allowed_emails = ["your_email@gmail.com", "friend@gmail.com"]
